jobs:
  pyinstaller-build:
    runs-on: windows-latest
    steps:
      - name: void
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.9'
          spec: 'poren_analyse.spec'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'void'
          options: --onefile, --name "My App", --windowed, 
