name: Build Workflow

on:
  push:
#    branches: master

jobs:
  build-windows:
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.9'
          architecture: 'x64'
      - name: Install requirements
        run: |
          pip install -r requirements.txt
      - name: Run PyInstaller
        run: |
          python -m PyInstaller poren_analyse.spec
      - uses: actions/upload-artifact@v2
        with:
          name: poren_analyse
          path: dist/poren_analyse.py.exe

      - name: Upload .exe
        uses: actions/upload-artifact@v2
        with:
          name: poren_analyse
          path: poren_analyse.exe
